plugins {
    id 'application'
    id 'checkstyle'
    id "com.github.spotbugs" version "5.0.14"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

checkstyle {
    toolVersion = '10.12.5'
    sourceSets = [sourceSets.main, sourceSets.test]
    ignoreFailures = false
}

spotbugs {
    toolVersion = '4.9.8'
    ignoreFailures = false
}

application {
    mainClass = 'edu.sandiego.comp305.StringUtils'
}

tasks.named('test') {
    useJUnitPlatform()
    mustRunAfter tasks.named('spotbugsMain')
    mustRunAfter tasks.named('spotbugsTest')
}